server:
  port: 8000
  servlet.contextpath: /shop
  session.timeout: 60000

logging:
  level:
    root: warn
    com.jl: info
    org.springframwork: warn
    com.jl.repository: debug
  file:
    path: ./logs
    name: jl_shop.log

spring:
  profiles:
    active: dev

mybatis:
  typeAliasesPackage: com.jl.bean
  mapper-locations: classpath:com/jl/repository/*.xml

---
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/db_fresh
    type: com.alibaba.druid.pool.DruidDataSource
